language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
env:
    - TEST_DIR=tests
script:
    - cd $TEST_DIR && py.test test.py --cov --ignore=/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/
after_success:
    - coveralls