language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
env:
    - TEST_DIR=tests
script:
    - cd $TEST_DIR && pytest test.py
after_success:
    - if [[ $ENV == python=3.6* ]]; then
          coveralls;
      fi